#:schema node_modules/wrangler/config-schema.json
name = "sublink"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "5c2bd69a3c7d45fd874d8131b985cf1f" }
]
